format = """
$direnv\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$conda\
$python\
\n$character\
"""

right_format = """
$cmd_duration
$lua
$rust
$time
$custom.o
"""

# ======================
# Directory
# ======================
[directory]
truncation_length = 6
truncation_symbol = 'ï¼ ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = '~'
style = 'fg:#7aa2f7'
read_only = ' ó°Œ¾ '
read_only_style = 'fg:#f7768e'
format = '[$path]($style)[$read_only]($read_only_style)'

# ======================
# Git
# ======================
[git_branch]
symbol = 'ï„¦ '
truncation_length = 4
truncation_symbol = ''
style = 'fg:#7aa2f7'
format = '[ $symbol$branch(:$remote_branch)]($style)'

[git_status]
style = 'fg:#e0af68'
conflicted = '='
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•'
up_to_date = 'âœ“'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = 'Â»'
deleted = 'âœ˜'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a'
deleted_style = 'fg:#9ece6a'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

# ======================
# Fill (ãƒ©ã‚¤ãƒ³)
# ======================
[fill]
symbol = 'â”€'
style = 'blue'

# ======================
# Conda (Python Blue)
# ======================
[conda]
symbol = 'îœ¼ '
style = 'fg:#306998'     # Python Blue
format = '[ $symbol$environment ]($style)'
ignore_base = false

# ======================
# Python (Python Yellow)
# ======================
[python]
symbol = 'îœ¼ '
style = 'fg:#FFD43B'     # Python Yellow
pyenv_version_name = false
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

# ======================
# Direnv
# ======================
[direnv]
format = '[ $symbol$allowed ]($style) '
style = "bold fg:#1a1b26"
disabled = false

# ======================
# Character (prompt)
# ======================
[character]
success_symbol = '[â¯](bold #FFD43B)'   # Python Yellow
error_symbol   = '[â¯](bold red)'

# ======================
# Command duration
# ======================
[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[ $duration ]($style)"

# ======================
# Lua
# ======================
[lua]
symbol = "î˜ "
format = '[ $symbol $version ](blue)'

# ======================
# Rust
# ======================
[rust]
symbol = "î¨"
format = '[ $symbol $version ](red)'

# ======================
# Time
# ======================
[time]
disabled = false
style = 'fg:#73daca'
format = '[ ï€— $time ]($style)'
time_format = '%T'
utc_time_offset = '+9'

[custom.o]
when = 'colima status 2>&1 | grep -qE "(^| )is running( |$)"'
command = 'echo ğŸ³'
format = "$output"   # â† ã“ã‚Œã§åå‰ã‚„è¨˜å·ã¯å‡ºãªã„
symbol = ""          # â† å¿µã®ãŸã‚ç©ºã«å›ºå®š
